install:
  - "echo ${PWD} && ls -l && cd ${TEST_DIR} && echo ${PWD} && bundle install"
script:
  - "echo ${PWD} && ls -l && cd ${TEST_DIR} && echo ${PWD} && COVERAGE=1 bundle exec cucumber"
os:
  - linux
  - osx
language: ruby
rvm:
  - 1.9.3  
  - 2.0.0
notifications:
  email:
    recipients:
      - foss@spritecloud.com
env:
  - TEST_DIR=test
