install:
  - "cd test"
  - "bundle install"
script:
  - "cd test"
  - "COVERAGE=1 bundle exec cucumber"
os:
  - linux
  - osx
language: ruby
rvm:
  - 1.9.3  
  - 2.0.0
notifications:
  email:
    recipients:
      - foss@spritecloud.com
